model:
  path: ../../vlcache/model_4b

data:
  path: data.jsonl
  micro_batch_size: 2
  seq_len: 2048
  gradient_accumulation_steps: 2

optimizer:
  lr: 1e-5
  min_lr: 1e-6
  weight_decay: 0.01
  adam_beta1: 0.9
  adam_beta2: 0.95
  adam_eps: 1e-8
  clip_grad: 1.0
  warmup_steps: 100
  total_steps: 2000

parallelism:
  tp: 2
  port: 2333

checkpoint:
  save_dir: checkpoints
  save_every: 500
  # resume_from: checkpoints/step_500